# Form implementation generated from reading ui file 'SendEmailGUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QFileDialog
from pathlib import Path

from util.CSVProcess import CSVProcessor
from util.MailProcess import MailProcess
from util.StringProcess import StringProcess


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 735)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 981, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(40, 30, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 361, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(540, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openClientListFile)
        self.subjectlabel = QtWidgets.QLabel(parent=self.tab)
        self.subjectlabel.setGeometry(QtCore.QRect(40, 60, 111, 16))
        self.subjectlabel.setObjectName("subjectlabel")
        self.subjectlineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.subjectlineEdit.setGeometry(QtCore.QRect(160, 60, 361, 22))
        self.subjectlineEdit.setObjectName("subjectlineEdit")
        self.emaillabel = QtWidgets.QLabel(parent=self.tab)
        self.emaillabel.setGeometry(QtCore.QRect(40, 90, 111, 16))
        self.emaillabel.setObjectName("emaillabel")
        self.emaillineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.emaillineEdit.setGeometry(QtCore.QRect(160, 90, 361, 22))
        self.emaillineEdit.setObjectName("emaillineEdit")
        self.textEdit = QtWidgets.QTextEdit(parent=self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 961, 551))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.smtphostlineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.smtphostlineEdit.setGeometry(QtCore.QRect(190, 30, 281, 22))
        self.smtphostlineEdit.setObjectName("smtphostlineEdit")
        self.smtphostlineEdit.setText("smtp.gmail.com")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(110, 80, 71, 20))
        self.label_3.setObjectName("label_3")
        self.smtpportlineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.smtpportlineEdit.setGeometry(QtCore.QRect(190, 80, 281, 22))
        self.smtpportlineEdit.setObjectName("smtpportlineEdit")
        self.smtpportlineEdit.setText("465")
        self.usernamelineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.usernamelineEdit.setGeometry(QtCore.QRect(190, 130, 281, 22))
        self.usernamelineEdit.setObjectName("usernamelineEdit")
        self.usernamelineEdit.setText("jliudadao@gmail.com")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(90, 130, 91, 20))
        self.label_4.setObjectName("label_4")
        self.passwordlineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.passwordlineEdit.setGeometry(QtCore.QRect(190, 180, 281, 22))
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.passwordlineEdit.setText("tpww hafr dycf xxqh")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(110, 180, 71, 20))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 650, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.sendEmails)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 650, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择客户名单文件"))
        self.pushButton.setText(_translate("MainWindow", "Open File"))
        self.subjectlabel.setText(_translate("MainWindow", "邮件主题"))
        self.emaillabel.setText(_translate("MainWindow", "邮件列名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发送邮件"))
        self.label_2.setText(_translate("MainWindow", "SMTP Host:"))
        self.label_3.setText(_translate("MainWindow", "SMTP Port:"))
        self.label_4.setText(_translate("MainWindow", "Email Address:"))
        self.label_5.setText(_translate("MainWindow", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Email账户设置"))
        self.pushButton_2.setText(_translate("MainWindow", "发送邮件"))
        self.pushButton_3.setText(_translate("MainWindow", "退出"))

    def openClientListFile(self):
        filename, ok = QFileDialog.getOpenFileName(
            self,
            "Select a File",
            "C:\\",
            "csv (*.csv *.jpg)"
        )
        if filename:
            path = Path(filename)
            self.lineEdit.setText(str(path))

    def sendEmails(self):
        email_text = self.textEdit.toHtml()
        csvfilename = self.lineEdit.text()
        subject = self.subjectlineEdit.text()
        email = self.emaillineEdit.text()
        sp = StringProcess()
        colname_list = sp.findColNames(email_text)
        csvp = CSVProcessor()
        multiColVal_list = csvp.readMultiColValue(csvfilename, colname_list)
        email_list = csvp.readColValue(csvfilename, email)

        imap_ssl_host = 'imap.gmail.com'
        smtp_host = self.smtphostlineEdit.text()#'smtp.gmail.com'
        smtp_port = int(self.smtpportlineEdit.text())#465
        username = self.usernamelineEdit.text()#'jliudadao@gmail.com'
        password = self.passwordlineEdit.text()#'tpww hafr dycf xxqh'

        mp = MailProcess()
        #mp.sendHTMLEmail_SMTP(smtp_host, smtp_port, username, password, "smarty", "liujinguccello@gmail.com", "test", email_text )
        mp.sendHTMLToAllEmail_SMTP(smtp_host, smtp_port, username, password,
                                   email_list, colname_list, multiColVal_list, subject, email_text)

if __name__ == '__main__':
    import sys

    app = QApplication(sys.argv)
    gallery = Ui_MainWindow()
    gallery.show()
    sys.exit(app.exec())